/*
* This file is part of Wakanda software, licensed by 4D under
*  (i) the GNU General Public License version 3 (GNU GPL v3), or
*  (ii) the Affero General Public License version 3 (AGPL v3) or
*  (iii) a commercial license.
* This file remains the exclusive property of 4D and/or its licensors
* and is protected by national and international legislations.
* In any event, Licensee's compliance with the terms and conditions
* of the applicable license constitutes a prerequisite to any use of this file.
* Except as otherwise expressly stated in the applicable license,
* such license does not include any other license or rights on this file,
* 4D's and/or its licensors' trademarks and/or other proprietary rights.
* Consequently, no title, copyright or other proprietary rights
* other than those specified in the applicable license is granted.
*/
/**
 * Fake Data for testing the GUI Designer
 * @namespace Designer.test
 */

Designer.test = {

    // JSON for an empty page
    htmlJson : 
    {
        "document":[{
            "nodeType":10,
            "name":"html"
        },{
            "nodeType":1,
            "nodeName":"html",
            "childNodes":[{
                "nodeType":3,
                "nodeValue":"\n    "
            },{
                "nodeType":1,
                "nodeName":"head",
                "childNodes":[{
                    "nodeType":3,
                    "nodeValue":"\n        "
                },{
                    "nodeType":1,
                    "nodeName":"title",
                    "childNodes":[{
                        "nodeType":3,
                        "nodeValue":"fffff"
                    }]
                },{
                    "nodeType":3,
                    "nodeValue":"\n        "
                },{
                    "nodeType":1,
                    "nodeName":"meta",
                    "attributes":{
                        "http-equiv":"Content-Type",
                        "content":"text\/html; charset=UTF-8"
                    }
                },{
                    "nodeType":3,
                    "nodeValue":"\n        "
                },{
                    "nodeType":1,
                    "nodeName":"meta",
                    "attributes":{
                        "name":"generator",
                        "content":"Wakanda GUIDesigner"
                    }
                },{
                    "nodeType":3,
                    "nodeValue":"\n        "
                },{
                    "nodeType":1,
                    "nodeName":"meta",
                    "attributes":{
                        "http-equiv":"X-UA-Compatible",
                        "content":"IE=Edge"
                    }
                },{
                    "nodeType":3,
                    "nodeValue":"\n    "
                }]
            },{
                "nodeType":3,
                "nodeValue":"\n    "
            },{
                "nodeType":1,
                "nodeName":"body",
                "childNodes":[{
                    "nodeType":3,
                    "nodeValue":"\n    "
                }]
            },{
                "nodeType":3,
                "nodeValue":"\n"
            }]
        }]
    }
    ,
    // Basic catalog for test
    catalog :
    {
        "dataClasses":[{
            "name":"courses",
            "singleEntityName":"course",
            "extraProperties":{
                "panel":{
                    "isOpen":"true",
                    "pathVisible":"true",
                    "position":{
                        "X":"646",
                        "Y":"476"
                    }
                }
            },
            "attributes":[{
                "name":"ID",
                "kind":"storage",
                "type":"long",
                "identifying":true
            },{
                "name":"teacher",
                "kind":"relatedEntity",
                "type":"teachers"
            },{
                "name":"student",
                "kind":"relatedEntity",
                "type":"students"
            },{
                "name":"room",
                "kind":"relatedEntity",
                "type":"rooms"
            },{
                "name":"matter",
                "kind":"storage",
                "type":"string"
            }],
            "key":[{
                "name":"ID"
            }]
        },{
            "name":"people",
            "singleEntityName":"person",
            "extraProperties":{
                "methVisible":"true",
                "relVisible":"true",
                "flatVisible":"false",
                "scalarVisible":"true",
                "panelColor":"rgb(183, 221, 232)",
                "panel":{
                    "isOpen":"true",
                    "pathVisible":"false",
                    "position":{
                        "X":"222",
                        "Y":"15"
                    }
                }
            },
            "attributes":[{
                "name":"ID",
                "kind":"storage",
                "type":"long",
                "identifying":true
            },{
                "name":"firstname",
                "kind":"storage",
                "type":"string",
                "autoComplete":true,
                "identifying":true
            },{
                "name":"name",
                "kind":"storage",
                "type":"string",
                "autoComplete":true,
                "identifying":true
            },{
                "name":"wages",
                "kind":"storage",
                "type":"number"
            },{
                "name":"studentID",
                "kind":"storage",
                "type":"string"
            },{
                "name":"teacherID",
                "kind":"storage",
                "type":"string"
            },{
                "name":"fullName",
                "kind":"calculated",
                "type":"string"
            },{
                "name":"father",
                "kind":"relatedEntity",
                "type":"people"
            },{
                "name":"mother",
                "kind":"relatedEntity",
                "type":"people"
            },{
                "name":"childrenAsFather",
                "kind":"relatedEntities",
                "type":"people"
            },{
                "name":"chlidrenAsMother",
                "kind":"relatedEntities",
                "type":"people"
            }],
            "methods":[{
                "name":"children",
                "applyTo":"entity",
                "from":"methods.people.children"
            },{
                "name":"display",
                "applyTo":"entitySet",
                "from":"methods.people.display"
            },{
                "name":"fakeData",
                "applyTo":"model",
                "from":"methods.people.fakeData"
            },{
                "name":"getFullNames",
                "applyTo":"model",
                "from":"methods.people.getFullNames"
            },{
                "name":"stuffnames",
                "applyTo":"entitySet",
                "from":"methods.people.stuffnames"
            }],
            "key":[{
                "name":"ID"
            }]
        },{
            "name":"rooms",
            "singleEntityName":"room",
            "extraProperties":{
                "panel":{
                    "isOpen":"true",
                    "pathVisible":"false",
                    "position":{
                        "X":"1125",
                        "Y":"877"
                    }
                }
            },
            "attributes":[{
                "name":"ID",
                "kind":"storage",
                "type":"long",
                "identifying":true
            },{
                "name":"name",
                "kind":"storage",
                "type":"string"
            }],
            "key":[{
                "name":"ID"
            }]
        },{
            "name":"students",
            "singleEntityName":"student",
            "extraProperties":{
                "panel":{
                    "isOpen":"true",
                    "pathVisible":"true",
                    "position":{
                        "X":"233",
                        "Y":"466"
                    }
                }
            },
            "attributes":[{
                "name":"ID",
                "kind":"storage",
                "type":"long",
                "identifying":true
            },{
                "name":"firstname",
                "kind":"storage",
                "type":"string",
                "autoComplete":true,
                "identifying":true
            },{
                "name":"name",
                "kind":"storage",
                "type":"string",
                "autoComplete":true,
                "identifying":true
            },{
                "name":"studentID",
                "kind":"storage",
                "type":"string"
            },{
                "name":"fullName",
                "kind":"calculated"
            },{
                "name":"father",
                "kind":"relatedEntity",
                "type":"people"
            },{
                "name":"mother",
                "kind":"relatedEntity",
                "type":"people"
            },{
                "name":"childrenAsFather",
                "kind":"relatedEntities",
                "type":"people"
            },{
                "name":"chlidrenAsMother",
                "kind":"relatedEntities",
                "type":"people"
            },{
                "name":"courses",
                "kind":"relatedEntities",
                "type":"courses"
            },{
                "name":"teachers",
                "kind":"relatedEntities",
                "type":"teachers"
            }],
            "event":[{
                "kind":"init",
                "from":"methods.students.events.init"
            }],
            "methods":[{
                "name":"children",
                "applyTo":"entity",
                "from":"methods.people.children"
            },{
                "name":"display",
                "applyTo":"entitySet",
                "from":"methods.people.display"
            },{
                "name":"fakeData",
                "applyTo":"model",
                "from":"methods.people.fakeData"
            },{
                "name":"getFullNames",
                "applyTo":"model",
                "from":"methods.people.getFullNames"
            },{
                "name":"newID",
                "applyTo":"model",
                "from":"methods.students.newID"
            },{
                "name":"stuffnames",
                "applyTo":"entitySet",
                "from":"methods.people.stuffnames"
            }],
            "key":[{
                "name":"ID"
            }]
        },{
            "name":"teachers",
            "singleEntityName":"teacher",
            "extraProperties":{
                "panel":{
                    "isOpen":"true",
                    "pathVisible":"true",
                    "position":{
                        "X":"1043",
                        "Y":"181"
                    }
                }
            },
            "attributes":[{
                "name":"ID",
                "kind":"storage",
                "type":"long",
                "identifying":true
            },{
                "name":"firstname",
                "kind":"storage",
                "type":"string",
                "autoComplete":true,
                "identifying":true
            },{
                "name":"name",
                "kind":"storage",
                "type":"string",
                "autoComplete":true,
                "identifying":true
            },{
                "name":"wages",
                "kind":"storage",
                "type":"number"
            },{
                "name":"teacherID",
                "kind":"storage",
                "type":"string"
            },{
                "name":"fullName",
                "kind":"calculated"
            },{
                "name":"father",
                "kind":"relatedEntity",
                "type":"people"
            },{
                "name":"mother",
                "kind":"relatedEntity",
                "type":"people"
            },{
                "name":"childrenAsFather",
                "kind":"relatedEntities",
                "type":"people"
            },{
                "name":"chlidrenAsMother",
                "kind":"relatedEntities",
                "type":"people"
            },{
                "name":"courses",
                "kind":"relatedEntities",
                "type":"courses"
            },{
                "name":"students",
                "kind":"relatedEntities",
                "type":"students"
            }],
            "event":[{
                "kind":"init",
                "from":"methods.teachers.events.init"
            }],
            "methods":[{
                "name":"children",
                "applyTo":"entity",
                "from":"methods.people.children"
            },{
                "name":"display",
                "applyTo":"entitySet",
                "from":"methods.people.display"
            },{
                "name":"fakeData",
                "applyTo":"model",
                "from":"methods.people.fakeData"
            },{
                "name":"getFullNames",
                "applyTo":"model",
                "from":"methods.people.getFullNames"
            },{
                "name":"newID",
                "applyTo":"model",
                "from":"methods.teachers.newID"
            },{
                "name":"stuffnames",
                "applyTo":"entitySet",
                "from":"methods.people.stuffnames"
            },{
                "name":"sumWages",
                "applyTo":"entitySet",
                "from":"methods.teachers.sumWages"
            }],
            "key":[{
                "name":"ID"
            }]
        }]
    },
	
    // CSS for the page    
    css : '',
	
    walib : {
        folder : ''
    }

}